Repository hmrc/tai-frontend, pull requests merged in 2018-12, with the labels that each got.

#258 ST-417: amended layout of pension error message
  app/views/incomes/editPension.scala.html
  conf/messages
  conf/messages.cy
Labels: Passed Review :+1:, Team 8

#262 ST-link: removing link to previous years tax code
  app/views/paye/historicPayAsYouEarn.scala.html
Labels: Passed Review :+1:

#266 ST-418: Add GA Event tags for EstPay CY+1 Journey
  app/views/incomeTaxComparison/IncomeSummary.scala.html
  app/views/incomeTaxComparison/Main.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Confirm.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Edit.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Start.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Success.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Template.scala.html
Labels: Team 8

#269 ST-418-2: Update CY+1 Estimated Journey after QA
  app/views/incomeTaxComparison/IncomeSummary.scala.html
  app/views/incomeTaxComparison/Main.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Template.scala.html
Labels: Team 8

#273 ST-416: Update to 2/3 layout
  app/assets/sass/tai05102018.scss
  app/views/incomes/bonusPaymentAmount.scala.html
  app/views/incomes/bonusPayments.scala.html
  app/views/incomes/confirmAmountEntered.scala.html
  app/views/incomes/confirm_save_Income.scala.html
  app/views/incomes/editIncome.scala.html
  app/views/incomes/editIncomeIrregularHours.scala.html
  app/views/incomes/editPension.scala.html
  app/views/incomes/estimatedPay.scala.html
  app/views/incomes/estimatedPayLandingPage.scala.html
  app/views/incomes/howToUpdate.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Template.scala.html
  app/views/incomes/payPeriod.scala.html
  app/views/incomes/payslipAmount.scala.html
  app/views/incomes/payslipDeductions.scala.html
  app/views/incomes/taxablePayslipAmount.scala.html
  app/views/incomes/workingHours.scala.html
  app/views/taxCodeChange/taxCodeComparison.scala.html
Labels: Team 8

#270 ST-299-a: Welsh amendments as per request. Including Welsh changes fo…
  conf/messages
  conf/messages.cy
Labels: Team 8
