Repository hmrc/tai-frontend, pull requests merged in 2018-10, with the labels that each got.

#176 ST-297: text box for estimated income resized
  app/assets/sass/tai03092018.scss
  app/views/incomes/editIncome.scala.html
  app/views/incomes/editPension.scala.html
Labels: Team 8

#177 ST-288-fix: Add employment name to update pension income screen
  app/views/incomes/editPension.scala.html
  test/views/html/incomes/EditPensionSpec.scala
Labels: Team 8

#175 ST-296: Remove blue heading from Estimated Pay
  app/assets/sass/tai03092018.scss
  app/views/incomes/bonusPaymentAmount.scala.html
  app/views/incomes/calcUnavailable.scala.html
  app/views/incomes/confirm_save_Income.scala.html
  app/views/incomes/editIncome.scala.html
  app/views/incomes/editPension.scala.html
  app/views/incomes/editSuccess.scala.html
  app/views/incomes/estimatedPay.scala.html
Labels: Team 8

#178 ST-298: Update currency text input to include symbol in input
  app/assets/sass/modules/_text-input.scss
  app/assets/sass/tai03092018.scss
  app/views/includes/forms/input.scala.html
  app/views/incomes/bonusPaymentAmount.scala.html
  app/views/incomes/payslipAmount.scala.html
  app/views/incomes/taxablePayslipAmount.scala.html
Labels: Passed QA, Team 8

#183 ST-292 - Income Calculator content updates
  app/views/incomes/bonusPaymentAmount.scala.html
  app/views/incomes/bonusPayments.scala.html
  app/views/incomes/estimatedPay.scala.html
  app/views/incomes/payPeriod.scala.html
  app/views/incomes/payslipAmount.scala.html
  app/views/incomes/payslipDeductions.scala.html
  app/views/incomes/taxablePayslipAmount.scala.html
  app/views/incomes/workingHours.scala.html
  conf/messages
  conf/messages.cy
  test/views/html/incomes/BonusPaymentsSpec.scala
  test/views/html/incomes/EstimatedPaySpec.scala
  test/views/html/incomes/PayPeriodSpec.scala
  test/views/html/incomes/PaySlipAmountSpec.scala
  test/views/html/incomes/PaySlipDeductionsSpec.scala
  test/views/html/incomes/WorkingHoursSpec.scala
Labels: Team 8

#181 ST-290: updated content for Simple Estimated Income journey
  app/assets/sass/modules/_typography.scss
  app/controllers/IncomeController.scala
  app/uk/gov/hmrc/tai/forms/EditIncomeForm.scala
  app/uk/gov/hmrc/tai/util/DateHelper.scala
  app/views/incomes/confirm_save_Income.scala.html
  app/views/incomes/editIncome.scala.html
  app/views/incomes/howToUpdate.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/IncomeControllerSpec.scala
  test/controllers/IncomeUpdateCalculatorControllerSpec.scala
  test/views/html/incomes/howToUpdateSpec.scala
Labels: Passed QA, Team 8

#189 ST-312: Change message for whole pounds error
  app/assets/sass/tai05102018.scss
  app/views/incomes/editIncome.scala.html
  app/views/incomes/editPension.scala.html
  conf/messages
  conf/messages.cy
Labels: Passed Review :+1:, Team 8

#188 ST-294 Check your answers
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  app/uk/gov/hmrc/tai/cacheResolver/estimatedPay/UpdatedEstimatedPayJourneyCache.scala
  app/uk/gov/hmrc/tai/service/IncomeService.scala
  app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/CheckYourAnswersViewModel.scala
  app/views/IncomeSourceSummary.scala.html
  app/views/benefits/removeCompnanyBenefitCheckYourAnswers.scala.html
  app/views/includes/checkYourAnswers.scala.html
  app/views/incomes/bonusPaymentAmount.scala.html
  app/views/incomes/bonusPayments.scala.html
  app/views/incomes/estimatedPay.scala.html
  app/views/incomes/estimatedPayment/update/checkYourAnswers.scala.html
  app/views/incomes/howToUpdate.scala.html
  app/views/incomes/incorrectTaxableIncome.scala.html
  app/views/incomes/payPeriod.scala.html
  app/views/incomes/payslipAmount.scala.html
  app/views/incomes/payslipDeductions.scala.html
  app/views/incomes/taxablePayslipAmount.scala.html
  app/views/incomes/workingHours.scala.html
  app/views/incomes/yourIncomeCalculation.scala.html
  conf/messages
  conf/messages.cy
  conf/tai.routes
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
  test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
  test/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/CheckYourAnswersViewModelSpec.scala
  test/views/html/IncomeSourceSummaryViewSpec.scala
  test/views/html/incomes/estimatedPayment/update/CheckYourAnswersSpec.scala
  test/views/html/incomes/yourIncomeCalculationSpec.scala
Labels: Passed Review :+1:, Team 8

#185 ST-295: Added landing page for update estimated income journey
  app/controllers/IncomeController.scala
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  app/views/IncomeSourceSummary.scala.html
  app/views/incomes/estimatedPayLandingPage.scala.html
  app/views/incomes/howToUpdate.scala.html
  conf/messages
  conf/messages.cy
  conf/tai.routes
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
  test/views/html/IncomeSourceSummaryViewSpec.scala
  test/views/html/incomes/EstimatedPayLandingPageSpec.scala
Labels: Team 8

#192 ST-315: EditIncome reformat entering yearly amount
  app/views/incomes/editIncome.scala.html
  conf/messages
  conf/messages.cy
Labels: Passed QA :+1:, Team 8

#199 ST-327: updated content for edit Income and edit Pension pages
  app/controllers/IncomeSourceSummaryController.scala
  app/views/incomes/editIncome.scala.html
  app/views/incomes/editPension.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/IncomeControllerSpec.scala
  test/views/html/incomes/EditIncomeSpec.scala
  test/views/html/incomes/EditPensionSpec.scala
Labels: Team 8

#203 ST-328: Updated content for check your updated amount page
  app/views/incomes/confirm_save_Income.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
Labels: Team 8

#206 ST-345: Changed the h1 title 'Beginning page of CY Pension Journey'
  app/views/incomes/estimatedPayLandingPage.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
  test/views/html/incomes/EstimatedPayLandingPageSpec.scala
Labels: Passed Review :+1:, Team 8

#208 ST-340: Updated content for bonus question on check your answers page
  app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/CheckYourAnswersViewModel.scala
  conf/messages
  conf/messages.cy
  test/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/CheckYourAnswersViewModelSpec.scala
Labels: Passed Review :+1:, Team 8

#210 ST-335:Updated content for total pay from payslip page
  app/uk/gov/hmrc/tai/forms/IncomeCalculatorForm.scala
  app/views/incomes/payslipAmount.scala.html
  conf/messages
  conf/messages.cy
Labels: Passed Review :+1:, Team 8

#202 ST-299 ST-333 - Irregular hours journey with updated text
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  app/uk/gov/hmrc/tai/forms/EditIncomeIrregularHoursForm.scala
  app/uk/gov/hmrc/tai/forms/IncomeCalculatorForm.scala
  app/uk/gov/hmrc/tai/service/TaxAccountService.scala
  app/uk/gov/hmrc/tai/util/TaiConstants.scala
  app/uk/gov/hmrc/tai/util/constants/EditIncomeIrregularPayConstants.scala
  app/uk/gov/hmrc/tai/viewModels/income/ConfirmIncomeIrregularHoursViewModel.scala
  app/uk/gov/hmrc/tai/viewModels/income/EditIncomeIrregularHoursViewModel.scala
  app/views/includes/forms/input.scala.html
  app/views/incomes/confirmIncomeIrregularHours.scala.html
  app/views/incomes/editIncomeIrregularHours.scala.html
  app/views/incomes/workingHours.scala.html
  conf/messages
  conf/messages.cy
  conf/tai.routes
  test/builders/RequestBuilder.scala
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
  test/uk/gov/hmrc/tai/service/TaxAccountServiceSpec.scala
  test/uk/gov/hmrc/tai/util/MessagesSpec.scala
  test/views/html/incomes/ConfirmIncomeIrregularHoursSpec.scala
  test/views/html/incomes/EditIncomeIrregularHoursSpec.scala
Labels: Passed Review :+1:, Team 8

#213 ST-349: Updated content for error message on update estimated income
  conf/messages
  conf/messages.cy
  test/views/html/incomes/EditIncomeIrregularHoursSpec.scala
Labels: Team 8

#220 ST-341: Content change for Estimated Pay page
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  app/uk/gov/hmrc/tai/util/MonetaryUtil.scala
  app/uk/gov/hmrc/tai/util/TaxYearRangeUtil.scala
  app/uk/gov/hmrc/tai/util/ViewModelHelper.scala
  app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/EstimatedPayViewModel.scala
  app/views/includes/cancelLink.scala.html
  app/views/incomes/estimatedPay.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
  test/uk/gov/hmrc/tai/util/MonetaryUtilSpec.scala
  test/uk/gov/hmrc/tai/util/TaxYearRangeUtilSpec.scala
  test/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/EstimatedPayViewModelSpec.scala
  test/views/html/incomes/EstimatedPaySpec.scala
Labels: Passed Review :+1:, Team 8

#222 ST-375
  app/uk/gov/hmrc/tai/util/TaxYearRangeUtil.scala
  app/uk/gov/hmrc/tai/util/ViewModelHelper.scala
  app/views/whatDoYouWantToDoTileView.scala.html
  conf/messages
  conf/messages.cy
  test/uk/gov/hmrc/tai/util/ViewModelHelperSpec.scala
  test/views/html/WhatDoYouWantToDoTileViewSpec.scala
Labels: Team 8
