Repository hmrc/tai-frontend, pull requests merged in 2018-11, with the labels that each got.

#221 Tax Code Mismatch - Handle 400 errors by returning hasTaxCodeChanged …
  app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
  test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceSpec.scala
Labels: Team 8

#224 Monetary bug fix: Fix for monetary formatting issues
  app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/CheckYourAnswersViewModel.scala
  test/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/CheckYourAnswersViewModelSpec.scala
Labels: Passed Review :+1:, Team 8

#226 ST-350 - How to Update, Working Hours, Pay Period translations
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  app/uk/gov/hmrc/tai/forms/IncomeCalculatorForm.scala
  app/uk/gov/hmrc/tai/util/constants/EditIncomePayPeriodConstants.scala
  app/views/incomes/payPeriod.scala.html
  conf/messages
  conf/messages.cy
  test/uk/gov/hmrc/tai/forms/IncomeCalculatorFormSpec.scala
Labels: Passed QA :+1:, Team 8

#228 ST-384 Spike
  app/controllers/income/UpdateIncomeNextYearController.scala
  app/uk/gov/hmrc/tai/connectors/JourneyCacheConnector.scala
  app/uk/gov/hmrc/tai/model/cache/UpdateNextYearsIncomeCacheModel.scala
  app/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeService.scala
  app/uk/gov/hmrc/tai/util/constants/JourneyCacheConstants.scala
  app/uk/gov/hmrc/tai/util/constants/journeyCache/UpdateNextYearsIncomeConstants.scala
  test/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeServiceSpec.scala
Labels: Team 8

#233 ST-384 split routes
  conf/application.conf
  conf/dev.routes
  conf/prod.routes
  conf/tai.routes
  project/Microservice.scala
Labels: Team 8

#219 Convert estimated pay update forms to consistent partial
  app/uk/gov/hmrc/tai/viewModels/income/EditIncomeIrregularHoursViewModel.scala
  app/views/includes/compareValueInput.scala.html
  app/views/incomes/editIncome.scala.html
  app/views/incomes/editIncomeIrregularHours.scala.html
  app/views/incomes/editPension.scala.html
  test/views/html/incomes/EditIncomeIrregularHoursSpec.scala
Labels: Team 8

#229 ST-384 - Skeleton for CY+1
  app/controllers/income/UpdateIncomeNextYearController.scala
  app/uk/gov/hmrc/tai/connectors/JourneyCacheConnector.scala
  app/uk/gov/hmrc/tai/model/cache/UpdateNextYearsIncomeCacheModel.scala
  app/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeService.scala
  app/uk/gov/hmrc/tai/util/constants/journeyCache/UpdateNextYearsIncomeConstants.scala
  app/views/incomes/nextYear/updateIncomeCYPlus1Confirm.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Edit.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Start.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Success.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Template.scala.html
  conf/application.conf
  conf/dev.routes
  conf/messages
  conf/messages.cy
  conf/prod.routes
  project/Microservice.scala
  test/controllers/income/UpdateIncomeNextYearControllerSpec.scala
  test/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeServiceSpec.scala
Labels: Team 8

#235 ST-view-matcher: create matcher to help with testing views from controllers
  test/controllers/ControllerViewTestHelper.scala
Labels: Team 8

#231 ST-338 Bonus page and Bonus page amount update
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  app/uk/gov/hmrc/tai/cacheResolver/estimatedPay/UpdatedEstimatedPayJourneyCache.scala
  app/uk/gov/hmrc/tai/forms/IncomeCalculatorForm.scala
  app/uk/gov/hmrc/tai/forms/YesNoForm.scala
  app/uk/gov/hmrc/tai/service/IncomeService.scala
  app/uk/gov/hmrc/tai/util/TaxYearRangeUtil.scala
  app/uk/gov/hmrc/tai/util/ViewModelHelper.scala
  app/uk/gov/hmrc/tai/util/constants/JourneyCacheConstants.scala
  app/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModel.scala
  app/uk/gov/hmrc/tai/viewModels/TaxFreeAmountViewModel.scala
  app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/CheckYourAnswersViewModel.scala
  app/views/includes/forms/inputRadioGroupStyling.scala.html
  app/views/incomes/bonusPaymentAmount.scala.html
  app/views/incomes/bonusPayments.scala.html
  app/views/incomes/estimatedPay.scala.html
  app/views/whatDoYouWantToDoTileView.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/TaxAccountSummaryControllerSpec.scala
  test/controllers/TaxFreeAmountControllerSpec.scala
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
  test/uk/gov/hmrc/tai/forms/YesNoFormSpec.scala
  test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
  test/uk/gov/hmrc/tai/util/TaxYearRangeUtilSpec.scala
  test/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModelSpec.scala
  test/uk/gov/hmrc/tai/viewModels/TaxFreeAmountViewModelSpec.scala
  test/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/CheckYourAnswersViewModelSpec.scala
  test/views/html/incomes/BonusPaymentsAmountSpec.scala
  test/views/html/incomes/BonusPaymentsSpec.scala
  test/views/html/incomes/estimatedPayment/update/CheckYourAnswersSpec.scala
Labels: Do not merge :stop_sign:, Team 8

#232 ST-367: set up controller and view for Estimated Pay CY Plus 1 Start page
  app/controllers/ErrorPagesHandler.scala
  app/controllers/auth/WithAuthorisedForTai.scala
  app/controllers/income/UpdateIncomeNextYearController.scala
  app/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeService.scala
  app/views/incomes/nextYear/updateIncomeCYPlus1Start.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/ControllerViewTestHelper.scala
  test/controllers/income/UpdateIncomeNextYearControllerSpec.scala
  test/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeServiceSpec.scala
  test/views/html/incomes/nextYear/updateIncomeCYPlus1StartSpec.scala
Labels: Team 8

#239 ST-370: Created Success page and controller and added relevant tests.
  app/controllers/income/UpdateIncomeNextYearController.scala
  app/views/incomes/nextYear/updateIncomeCYPlus1Success.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/income/UpdateIncomeNextYearControllerSpec.scala
  test/views/html/incomes/nextYear/updateIncomeCYPlus1EditSpec.scala
  test/views/html/incomes/nextYear/updateIncomeCYPlus1SuccessSpec.scala
Labels: Team 8

#247 Correct welsh quote for build
  conf/messages.cy
Labels: Team 8

#249 ST-364: Updated Estimated pay CY Plus 1 journey to include pensions
  app/controllers/income/UpdateIncomeNextYearController.scala
  app/uk/gov/hmrc/tai/model/cache/UpdateNextYearsIncomeCacheModel.scala
  app/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeService.scala
  app/uk/gov/hmrc/tai/util/constants/journeyCache/UpdateNextYearsIncomeConstants.scala
  app/views/incomes/nextYear/updateIncomeCYPlus1Edit.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Start.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Success.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/income/UpdateIncomeNextYearControllerSpec.scala
  test/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeServiceSpec.scala
  test/views/html/incomes/nextYear/updateIncomeCYPlus1EditSpec.scala
  test/views/html/incomes/nextYear/updateIncomeCYPlus1StartSpec.scala
  test/views/html/incomes/nextYear/updateIncomeCYPlus1SuccessSpec.scala
Labels: Passed QA :+1:, Team 8

#245 ST-374
  app/uk/gov/hmrc/tai/viewModels/IncomeSourceComparisonViewModel.scala
  app/views/incomeTaxComparison/IncomeSummary.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/income/UpdateIncomeNextYearControllerSpec.scala
  test/uk/gov/hmrc/tai/viewModels/incomeTaxComparison/IncomeSourceComparisonViewModelSpec.scala
  test/views/html/incomeTaxComparison/IncomeSummarySpec.scala
Labels: Passed QA :+1:, Team 8

#248 ST-382 Updated error message for monetary amount fields
  app/uk/gov/hmrc/tai/forms/EditIncomeForm.scala
  app/uk/gov/hmrc/tai/forms/IncomeCalculatorForm.scala
  app/views/incomes/editIncome.scala.html
  app/views/incomes/editPension.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/IncomeControllerSpec.scala
  test/views/html/incomes/BonusPaymentsAmountSpec.scala
Labels: Passed QA :+1:, Team 8

#250 ST-396:content change on CY+1/same page cancel link
  conf/messages
  conf/messages.cy
Labels: Passed QA :+1:, Team 8

#251 ST-398 - What do you want to tile view update
  app/views/whatDoYouWantToDoTileView.scala.html
  conf/messages
  conf/messages.cy
  test/views/html/WhatDoYouWantToDoTileViewSpec.scala
Labels: Passed QA :+1:, Passed Review :+1:, Team 8
