Repository hmrc/tai-frontend, pull requests merged in 2019-03, with the labels that each got.

#468 ST-561: Resolve table styling bug
  app/views/incomeTaxComparison/TaxCodes.scala.html
Labels: PO/BA review pending, Passed QA :+1:, Passed Review :+1:

#466 ST-509: Pushing date to separate lines
  app/assets/sass/tai26022019.scss
  app/uk/gov/hmrc/tai/service/TaxPeriodLabelService.scala
  app/uk/gov/hmrc/tai/util/TaxYearRangeUtil.scala
  app/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModel.scala
  app/uk/gov/hmrc/tai/viewModels/income/ConfirmAmountEnteredViewModel.scala
  app/uk/gov/hmrc/tai/viewModels/income/previousYears/UpdateHistoricIncomeDetailsViewModel.scala
  app/views/IncomeSourceSummary.scala.html
  app/views/estimatedIncomeTax/complexEstimatedIncomeTax.scala.html
  app/views/includes/ptaHeader.scala.html
  app/views/incomeTaxSummary.scala.html
  app/views/incomes/editPension.scala.html
  app/views/incomes/estimatedPayLandingPage.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Same.scala.html
  app/views/paye/historicPayAsYouEarn.scala.html
  app/views/taxCodeChange/formattedTaxCodeForComparison.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/IncomeControllerSpec.scala
  test/controllers/IncomeSourceSummaryControllerSpec.scala
  test/controllers/TaxAccountSummaryControllerSpec.scala
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
  test/uk/gov/hmrc/tai/service/TaxPeriodLabelServiceSpec.scala
  test/uk/gov/hmrc/tai/util/TaxYearRangeUtilSpec.scala
  test/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModelSpec.scala
  test/uk/gov/hmrc/tai/viewModels/UpdateHistoricIncomeDetailsViewModelSpec.scala
  test/views/html/IncomeSourceSummaryViewSpec.scala
  test/views/html/incomes/EditPensionSpec.scala
  test/views/html/incomes/confirmAmountEnteredSpec.scala
  test/views/html/incomes/nextYear/UpdateIncomeCYPlus1Confirm.scala
  test/views/html/incomes/nextYear/updateIncomeCYPlus1SameSpec.scala
  test/views/html/incomes/previousYears/UpdateIncomeDetailsSpec.scala
  test/views/html/paye/historicPayAsYouEarnSpec.scala
Labels: PO/BA review pending, Pending QA, Team 8

#472 ST-430-welsh: Welsh amendment for ST-430
  conf/messages.cy
Labels: Pending QA, Team 8

#478 St 553 b
  app/controllers/employments/AddEmploymentController.scala
  app/controllers/employments/EndEmploymentController.scala
  app/controllers/employments/UpdateEmploymentController.scala
  app/controllers/pensions/AddPensionProviderController.scala
  app/controllers/pensions/UpdatePensionProviderController.scala
  app/uk/gov/hmrc/tai/viewModels/pensions/CheckYourAnswersViewModel.scala
  app/views/employments/add_employment_first_pay_form.scala.html
  app/views/employments/add_employment_name_form.scala.html
  app/views/employments/add_employment_payroll_number_form.scala.html
  app/views/employments/add_employment_start_date_form.scala.html
  app/views/employments/endEmployment.scala.html
  app/views/employments/update/UpdateEmploymentCheckYourAnswers.scala.html
  app/views/employments/update/whatDoYouWantToTellUs.scala.html
  app/views/employments/update_remove_employment_decision.scala.html
  app/views/pensions/addPensionName.scala.html
  app/views/pensions/addPensionNumber.scala.html
  app/views/pensions/addPensionReceivedFirstPay.scala.html
  app/views/pensions/addPensionStartDate.scala.html
  app/views/pensions/update/doYouGetThisPensionIncome.scala.html
  app/views/pensions/update/updatePensionCheckYourAnswers.scala.html
  app/views/pensions/update/whatDoYouWantToTellUs.scala.html
  conf/tai.routes
  test/controllers/employments/AddEmploymentControllerSpec.scala
  test/controllers/employments/EndEmploymentControllerSpec.scala
  test/controllers/employments/UpdateEmploymentControllerSpec.scala
  test/controllers/pensions/AddPensionProviderControllerSpec.scala
  test/controllers/pensions/UpdatePensionProviderControllerSpec.scala
  test/uk/gov/hmrc/tai/viewModels/pensions/CheckYourAnswersViewModelSpec.scala
  test/views/html/employments/AddEmploymentFirstPaySpec.scala
  test/views/html/employments/AddEmploymentNameFormSpec.scala
  test/views/html/employments/AddEmploymentPayrollNumberSpec.scala
  test/views/html/employments/AddEmploymentStartDateFormSpec.scala
  test/views/html/employments/UpdateRemoveEmploymentDecisionSpec.scala
  test/views/html/employments/endEmploymentSpec.scala
  test/views/html/employments/update/UpdateEmploymentCheckYourAnswersSpec.scala
  test/views/html/employments/update/WhatDoYouWantToTellUsSpec.scala
  test/views/html/pensions/AddPensionNameSpec.scala
  test/views/html/pensions/AddPensionNumberSpec.scala
  test/views/html/pensions/AddPensionReceivedFirstPaySpec.scala
  test/views/html/pensions/AddPensionStartDateSpec.scala
  test/views/html/pensions/DoYouGetThisPensionIncomePageSpec.scala
  test/views/html/pensions/updatePensions/UpdatePensionsCheckYourAnswersSpec.scala
  test/views/html/pensions/updatePensions/WhatDoYouWantToTellUsSpec.scala
Labels: Passed QA :+1:

#473 ST-435 Payslips now have dynamic titles
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
  app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/PaySlipAmountViewModel.scala
  app/views/includes/editIncomeWhatShouldYouInclude.scala.html
  app/views/incomes/bonusPaymentAmount.scala.html
  app/views/incomes/bonusPayments.scala.html
  app/views/incomes/editIncomeIrregularHours.scala.html
  app/views/incomes/payslipAmount.scala.html
  app/views/incomes/payslipDeductions.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
  test/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/EstimatedPayViewModelSpec.scala
  test/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/PaySlipAmountViewModelSpec.scala
  test/views/html/incomes/EditIncomeIrregularHoursSpec.scala
  test/views/html/incomes/PaySlipAmountSpec.scala
Labels: PO/BA reviewed :+1:, Passed QA :+1:

#467 ST-559 same estimated pay
  app/controllers/IncomeController.scala
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  app/views/incomes/confirm_save_Income.scala.html
  conf/tai.routes
  test/controllers/IncomeControllerSpec.scala
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
Labels: Passed QA :+1:

#475 ST-508: Update headings for long employe/pension names
  app/views/benefits/updateCompanyCar.scala.html
  app/views/employments/add_employment_payroll_number_form.scala.html
  app/views/employments/add_employment_start_date_form.scala.html
  app/views/incomes/confirmAmountEntered.scala.html
  app/views/incomes/editIncome.scala.html
  app/views/incomes/estimatedPay.scala.html
  app/views/incomes/historicIncomeCalculation.scala.html
  app/views/incomes/howToUpdate.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Start.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Template.scala.html
  app/views/pensions/addPensionNumber.scala.html
  app/views/pensions/addPensionReceivedFirstPay.scala.html
  app/views/pensions/addPensionStartDate.scala.html
Labels: PO/BA review pending, Pending QA, Team 8

#476 ST 566 Fix a screen reader link
  app/views/IncomeSourceSummary.scala.html
Labels: Pending QA

#487 ST-453:Updated error messages full year and irregular
  conf/messages
  conf/messages.cy
Labels: PO/BA review pending, Pending QA, Team 8

#489 ST-460: Update error message on Bonus page
  conf/messages
  conf/messages.cy
Labels: PO/BA review pending, Pending QA, Team 8

#490 ST-461: Update error message on Bonus enter page
  conf/messages
  conf/messages.cy
Labels: PO/BA review pending, Pending QA, Team 8

#491 ST-458: Updated error message gross pay invalid format
  conf/messages
  conf/messages.cy
Labels: PO/BA review pending, Pending QA, Team 8

#492 ST-508-2: Wrap around main headings
  app/views/employments/update/UpdateEmploymentCheckYourAnswers.scala.html
  app/views/employments/update/whatDoYouWantToTellUs.scala.html
  app/views/employments/update_remove_employment_decision.scala.html
  app/views/pensions/update/doYouGetThisPensionIncome.scala.html
  app/views/pensions/update/whatDoYouWantToTellUs.scala.html
  app/views/taxCodeChange/taxCodeComparison.scala.html
  test/views/html/taxCodeChange/TaxCodeComparisonViewSpec.scala
Labels: PO/BA review pending, Pending QA, Team 8

#498 ST-508-2:Wrap around main heading
  app/views/IncomeSourceSummary.scala.html
Labels: PO/BA review pending, Pending QA, Team 8

#497 ST-592: Add bullet to show number of current income sources
  app/uk/gov/hmrc/tai/model/domain/TaxCodeChange.scala
  app/uk/gov/hmrc/tai/util/yourTaxFreeAmount/TaxCodeChangeReasons.scala
  conf/messages
  conf/messages.cy
  test/uk/gov/hmrc/tai/util/yourTaxFreeAmount/TaxCodeChangeReasonsSpec.scala
Labels: Team 8

#500 ST-581: Updated link content on Income Tax summary page
  conf/messages
  conf/messages.cy
Labels: Team 8

#501 ST-453: Irregular and Yearly income update error messages
  conf/messages
  conf/messages.cy
Labels: Team 8

#495 ST-588 CY+1 banner
  app/controllers/IncomeTaxComparisonController.scala
  app/controllers/WhatDoYouWantToDoController.scala
  app/uk/gov/hmrc/tai/service/TrackingService.scala
  app/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeService.scala
  app/uk/gov/hmrc/tai/util/constants/journeyCache/UpdateNextYearsIncomeConstants.scala
  app/uk/gov/hmrc/tai/viewModels/incomeTaxComparison/IncomeTaxComparisonViewModel.scala
  app/views/incomeTaxComparison/Main.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/IncomeTaxComparisonControllerSpec.scala
  test/uk/gov/hmrc/tai/service/TrackingServiceSpec.scala
  test/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeServiceSpec.scala
  test/uk/gov/hmrc/tai/viewModels/incomeTaxComparison/IncomeTaxComparisonViewModelSpec.scala
  test/views/html/incomeTaxComparison/MainSpec.scala
Labels: Passed Review :+1:, Pending QA

#484 ST-585 Added the amount for new IABDs in dynamic text
  app/uk/gov/hmrc/tai/util/yourTaxFreeAmount/IabdTaxCodeChangeReasons.scala
  conf/messages
  conf/messages.cy
  test/uk/gov/hmrc/tai/util/yourTaxFreeAmount/IabdTaxCodeChangeReasonsSpec.scala
Labels: Change Requested

#486 ST-586 Amount for amending and IABD
  app/uk/gov/hmrc/tai/util/yourTaxFreeAmount/IabdTaxCodeChangeReasons.scala
  conf/messages
  conf/messages.cy
  test/uk/gov/hmrc/tai/util/yourTaxFreeAmount/IabdTaxCodeChangeReasonsSpec.scala
Labels: Change Requested

#505 ST-589: Updated IabdTaxCodeChangeReasons to 6 reasons and ordered
  app/uk/gov/hmrc/tai/model/domain/TaxCodeChange.scala
  app/uk/gov/hmrc/tai/service/yourTaxFreeAmount/TaxCodeChangeReasonsService.scala
  app/uk/gov/hmrc/tai/util/yourTaxFreeAmount/IabdTaxCodeChangeReasons.scala
  test/uk/gov/hmrc/tai/service/yourTaxFreeAmount/TaxCodeChangeReasonsServiceSpec.scala
  test/uk/gov/hmrc/tai/util/yourTaxFreeAmount/IabdTaxCodeChangeReasonsSpec.scala
Labels: Team 8

#507 ST-497: Add GA event tags to links on IncomeSourceSummary page
  app/views/IncomeSourceSummary.scala.html
  app/views/incomes/estimatedPayLandingPage.scala.html
Labels: Team 8

#510 ST-299: removed fullstop from welsh translation as requested
  conf/messages.cy
Labels: Passed Review :+1:, Team 8

#511 ST-499: Add GA Tagging for Estimated Pay HowToUpdate page
  app/views/incomes/howToUpdate.scala.html
Labels: Team 8

#515 ST-500: Add GA Tagging for Update Estimated Pay your working hours page
  app/views/incomes/workingHours.scala.html
Labels: Team 8

#517 ST-501: Add GA Tagging for edit annual income page
  app/views/incomes/editIncome.scala.html
Labels: Team 8

#516 ST-502: Add GA Tagging for edit income irregular hours page
  app/views/incomes/editIncomeIrregularHours.scala.html
Labels: Team 8

#518 ST-442-welsh: Welsh amendments for check your answer page
  conf/messages.cy
Labels: PO/BA review pending, Pending QA, Team 8
