Repository hmrc/tai-frontend, pull requests merged in 2019-01, with the labels that each got.

#327 ST-447: CompanyCarConnector now uses dependency injection
  app/uk/gov/hmrc/tai/config/TaiModule.scala
  app/uk/gov/hmrc/tai/connectors/CompanyCarConnector.scala
  app/uk/gov/hmrc/tai/service/benefits/CompanyCarService.scala
  test/uk/gov/hmrc/tai/connectors/CompanyCarConnectorSpec.scala
  test/uk/gov/hmrc/tai/service/benefits/CompanyCarServiceSpec.scala
Labels: Do not merge :stop_sign:

#362 Fix AuthClientAuthConnector (lazy val)
  app/uk/gov/hmrc/tai/config/TaiModule.scala
  app/uk/gov/hmrc/tai/connectors/AuthClientAuthConnector.scala
  conf/application.conf
Labels: Team 8

#356 ST-259: Remove Tax Code Change Toggle
  app/controllers/PayeControllerHistoric.scala
  app/controllers/TaxCodeChangeController.scala
  app/controllers/YourTaxCodeController.scala
  app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
  app/views/paye/historicPayAsYouEarn.scala.html
  test/controllers/PayeControllerHistoricSpec.scala
  test/controllers/TaxCodeChangeControllerSpec.scala
  test/controllers/YourTaxCodeControllerSpec.scala
  test/views/html/paye/historicPayAsYouEarnSpec.scala
Labels: Team 8

#355 ST-485: Feature toggle CY+1 estimated Pay
  app/controllers/IncomeTaxComparisonController.scala
  app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
  app/views/incomeTaxComparison/IncomeSummary.scala.html
  app/views/incomeTaxComparison/Main.scala.html
  test/views/html/incomeTaxComparison/IncomeSummarySpec.scala
  test/views/html/incomeTaxComparison/MainSpec.scala
Labels: Team 8

#368 Auth - Remove AffinityGroup to allow verify users
  app/controllers/auth/AuthAction.scala
  test/controllers/auth/AuthActionSpec.scala
Labels: Team 8

#374 AuthUpgrade - Deceased Controller
  app/controllers/DeceasedController.scala
  app/views/deceased_helpline.scala.html
  test/controllers/DeceasedControllerSpec.scala
  test/views/html/deceasedHelplinePageSpec.scala
Labels: Team 8

#375 Auth Upgrade - DetailedIncomeTaxEstimateController
  app/controllers/DetailedIncomeTaxEstimateController.scala
  app/views/estimatedIncomeTax/detailedIncomeTaxEstimate.scala.html
  test/controllers/DetailedIncomeTaxEstimateControllerSpec.scala
Labels: Team 8

#345 Responsive cy+1 comparison: Adding responsiveness to tables in CY plus one comparison page
  app/assets/sass/modules/_cy-plus-one-income-tax-comparison.scss
  app/assets/sass/tai05102018.scss
  app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
  app/uk/gov/hmrc/tai/viewModels/TaxFreeAmountComparisonViewModel.scala
  app/views/incomeTaxComparison/IncomeSummary.scala.html
  app/views/incomeTaxComparison/IncomeTax.scala.html
  app/views/incomeTaxComparison/TaxCodes.scala.html
  app/views/incomeTaxComparison/TaxFreeAmount.scala.html
  conf/application.conf
  conf/messages
  conf/messages.cy
  test/views/html/incomeTaxComparison/IncomeSummarySpec.scala
  test/views/html/incomeTaxComparison/IncomeTaxSpec.scala
  test/views/html/incomeTaxComparison/TaxCodesSpec.scala
  test/views/html/incomeTaxComparison/TaxFreeAmountSpec.scala
Labels: Pending QA, Team 8

#378 AuthUpgrade - Estimated Income Tax Controller
  app/controllers/EstimatedIncomeTaxController.scala
  app/views/estimatedIncomeTax/complexEstimatedIncomeTax.scala.html
  app/views/estimatedIncomeTax/noCurrentIncome.scala.html
  app/views/estimatedIncomeTax/simpleEstimatedIncomeTax.scala.html
  app/views/estimatedIncomeTax/zeroTaxEstimatedIncomeTax.scala.html
  test/controllers/EstimatedIncomeTaxControllerSpec.scala
Labels: Team 8

#382 AuthUpgrade - ExternalService, Help and YourTaxCode controller
  app/controllers/ExternalServiceRedirectController.scala
  app/controllers/HelpController.scala
  app/controllers/YourTaxCodeController.scala
  app/views/help/getHelp.scala.html
  test/controllers/ExternalServiceRedirectControllerSpec.scala
  test/controllers/HelpControllerSpec.scala
  test/controllers/YourTaxCodeControllerSpec.scala
  test/views/html/getHelpPageSpec.scala
Labels: Team 8

#385 AuthUpgrade - Employment, Pension Company Car controllers
  app/controllers/benefits/CompanyBenefitController.scala
  app/controllers/benefits/RemoveCompanyBenefitController.scala
  app/controllers/employments/AddEmploymentController.scala
  app/controllers/employments/EndEmploymentController.scala
  app/controllers/employments/UpdateEmploymentController.scala
  app/controllers/income/previousYears/UpdateIncomeDetailsController.scala
  app/controllers/pensions/AddPensionProviderController.scala
  app/controllers/pensions/UpdatePensionProviderController.scala
  app/views/benefits/removeBenefitTotalValue.scala.html
  app/views/benefits/removeCompanyBenefitCheckYourAnswers.scala.html
  app/views/benefits/removeCompanyBenefitConfirmation.scala.html
  app/views/benefits/removeCompanyBenefitStopDate.scala.html
  app/views/benefits/updateOrRemoveCompanyBenefitDecision.scala.html
  app/views/can_we_contact_by_phone.scala.html
  app/views/employments/EndEmploymentIrregularPaymentError.scala.html
  app/views/employments/add_employment_error_page.scala.html
  app/views/employments/add_employment_first_pay_form.scala.html
  app/views/employments/add_employment_name_form.scala.html
  app/views/employments/add_employment_payroll_number_form.scala.html
  app/views/employments/add_employment_start_date_form.scala.html
  app/views/employments/confirmation.scala.html
  app/views/employments/endEmployment.scala.html
  app/views/employments/endEmploymentWithinSixWeeksError.scala.html
  app/views/employments/update/UpdateEmploymentCheckYourAnswers.scala.html
  app/views/employments/update/whatDoYouWantToTellUs.scala.html
  app/views/employments/update_remove_employment_decision.scala.html
  app/views/incomes/addIncomeCheckYourAnswers.scala.html
  app/views/incomes/previousYears/CheckYourAnswers.scala.html
  app/views/incomes/previousYears/UpdateIncomeDetails.scala.html
  app/views/incomes/previousYears/UpdateIncomeDetailsConfirmation.scala.html
  app/views/incomes/previousYears/UpdateIncomeDetailsDecision.scala.html
  app/views/pensions/addPensionCheckYourAnswers.scala.html
  app/views/pensions/addPensionConfirmation.scala.html
  app/views/pensions/addPensionErrorPage.scala.html
  app/views/pensions/addPensionName.scala.html
  app/views/pensions/addPensionNumber.scala.html
  app/views/pensions/addPensionReceivedFirstPay.scala.html
  app/views/pensions/addPensionStartDate.scala.html
  app/views/pensions/update/confirmation.scala.html
  app/views/pensions/update/doYouGetThisPensionIncome.scala.html
  app/views/pensions/update/updatePensionCheckYourAnswers.scala.html
  app/views/pensions/update/whatDoYouWantToTellUs.scala.html
  test/controllers/benefits/CompanyBenefitControllerSpec.scala
  test/controllers/benefits/RemoveCompanyBenefitControllerSpec.scala
  test/controllers/employments/AddEmploymentControllerSpec.scala
  test/controllers/employments/EndEmploymentControllerSpec.scala
  test/controllers/employments/UpdateEmploymentControllerSpec.scala
  test/controllers/income/previousYears/UpdateIncomeDetailsControllerSpec.scala
  test/controllers/pensions/AddPensionProviderControllerSpec.scala
  test/controllers/pensions/UpdatePensionProviderControllerSpec.scala
Labels: Team 8

#389 Welsh changes - tax-free amount and cy+1 comaprison page
  conf/messages.cy
Labels: Team 8

#408 Revert "ST-475 end employment controller AUTH update"
  app/controllers/employments/AddEmploymentController.scala
  app/controllers/employments/EndEmploymentController.scala
  app/views/employments/EndEmploymentIrregularPaymentError.scala.html
  app/views/employments/endEmployment.scala.html
  app/views/employments/endEmploymentWithinSixWeeksError.scala.html
  app/views/employments/update_remove_employment_decision.scala.html
  test/controllers/employments/AddEmploymentControllerSpec.scala
  test/controllers/employments/EndEmploymentControllerSpec.scala
Labels: Passed Review :+1:

#405 Fix unauthorised redirect for all exceptions
  app/controllers/auth/AuthAction.scala
  test/controllers/auth/AuthActionSpec.scala
Labels: Team 8

#410 ST-475 update employment controller Auth update
  app/controllers/employments/UpdateEmploymentController.scala
  app/views/employments/update/UpdateEmploymentCheckYourAnswers.scala.html
  app/views/employments/update/whatDoYouWantToTellUs.scala.html
  test/controllers/employments/UpdateEmploymentControllerSpec.scala
Labels: Team 8

#413 AuthUpgrade - End Employment
  app/controllers/employments/AddEmploymentController.scala
  app/controllers/employments/EndEmploymentController.scala
  app/views/employments/EndEmploymentIrregularPaymentError.scala.html
  app/views/employments/endEmployment.scala.html
  app/views/employments/endEmploymentWithinSixWeeksError.scala.html
  app/views/employments/update_remove_employment_decision.scala.html
  test/controllers/employments/EndEmploymentControllerSpec.scala
Labels: Team 8
