Repository hmrc/tai-frontend, pull requests merged in 2019-04, with the labels that each got.

#519 ST-480: Google tag manager implementation
  app/views/main.scala.html
  conf/application.conf
  project/FrontendBuild.scala
Labels: PO/BA review pending, Pending QA, Team 8

#506 ST-459: Added dynamic messages for taxable pay
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  app/uk/gov/hmrc/tai/forms/IncomeCalculatorForm.scala
  app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/DynamicPayPeriodTitle.scala
  app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/PaySlipAmountViewModel.scala
  test/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/DynamicPayPeriodTitleSpec.scala
  test/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/TaxablePaySlipAmountViewModelSpec.scala
  test/views/html/incomes/TaxablePaySlipAmountSpec.scala
Labels: PO/BA review pending, Pending QA, Team 8

#521 ST-578: Updated link on Underpayment estimate page
  app/uk/gov/hmrc/tai/viewModels/PotentialUnderpaymentViewModel.scala
  test/uk/gov/hmrc/tai/viewModels/PotentialUnderpaymentViewModelSpec.scala
Labels: Team 8

#522 ST-580: Add link to Check your Income Tax estimate page
  app/views/taxCodeDetails.scala.html
  app/views/taxFreeAmount.scala.html
  conf/messages
  conf/messages.cy
  test/views/html/TaxCodeDetailsViewSpec.scala
  test/views/html/TaxFreeAmountViewSpec.scala
Labels: Team 8

#525 ST-579: updated headings on income tax summary page
  app/views/paye/historicPayAsYouEarn.scala.html
  conf/messages
  conf/messages.cy
  test/views/html/paye/historicPayAsYouEarnSpec.scala
Labels: Team 8

#520 ST-574: Fixed padding on bullet points
  app/assets/sass/modules/tax_code_change.scss
Labels: PO/BA review pending, Pending QA, Team 8

#530 ST-596: Updated underpayment links in all tax-free amount pages
  app/controllers/TaxFreeAmountController.scala
  app/uk/gov/hmrc/tai/model/CodingComponentPairModel.scala
  app/uk/gov/hmrc/tai/service/yourTaxFreeAmount/DescribedYourTaxFreeAmountService.scala
  app/uk/gov/hmrc/tai/viewModels/TaxFreeAmountSummaryViewModel.scala
  app/uk/gov/hmrc/tai/viewModels/TaxFreeAmountViewModel.scala
  app/uk/gov/hmrc/tai/viewModels/TaxSummaryLabel.scala
  conf/messages
  conf/messages.cy
  test/controllers/TaxFreeAmountControllerSpec.scala
  test/uk/gov/hmrc/tai/model/CodingComponentPairModelSpec.scala
  test/uk/gov/hmrc/tai/service/yourTaxFreeAmount/DescribedYourTaxFreeAmountServiceSpec.scala
  test/uk/gov/hmrc/tai/viewModels/TaxFreeAmountSummaryViewModelSpec.scala
  test/uk/gov/hmrc/tai/viewModels/TaxFreeAmountViewModelSpec.scala
  test/uk/gov/hmrc/tai/viewModels/TaxSummaryLabelSpec.scala
Labels: Team 8

#536 ST-596-fix: catch exceptions where underpayment has been coded prev y…
  app/uk/gov/hmrc/tai/viewModels/TaxSummaryLabel.scala
  test/uk/gov/hmrc/tai/viewModels/TaxSummaryLabelSpec.scala
Labels: Team 8

#532 ST-579:changed the styling of the tax code change tile
  app/views/whatDoYouWantToDoTileView.scala.html
Labels: Team 8

#541 ST-619: Updated styling and content on tax code comparision page
  app/views/taxCodeChange/taxCodeComparison.scala.html
  conf/messages
  conf/messages.cy
Labels: PO/BA review pending, Pending QA, Team 8

#547 St 471
  app/uk/gov/hmrc/tai/viewModels/income/ConfirmAmountEnteredViewModel.scala
  app/views/incomes/confirmAmountEntered.scala.html
  app/views/incomes/nextYear/updateIncomeCYPlus1Confirm.scala.html
  conf/messages
  conf/messages.cy
  test/views/html/incomes/confirmAmountEnteredSpec.scala
  test/views/html/incomes/nextYear/UpdateIncomeCYPlus1Confirm.scala
Labels: PO/BA review pending, Pending QA, Team 8

#552 dep-upgrade: Updated library dependencies to latest version
  project/FrontendBuild.scala
  project/plugins.sbt
Labels: Team 8

#553 ST-466-2: Removed comma
  conf/messages
  conf/messages.cy
Labels: PO/BA review pending, Team 8

#554 St 464
  conf/messages
  conf/messages.cy
Labels: Team 8

#560 updated contnet for cy +1 update estimated income
  conf/messages
  conf/messages.cy
Labels: Team 8

#542 ST-603: Add page to warn that est pay has been updated once already
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/DuplicateSubmissionEmploymentViewModel.scala
  app/views/IncomeSourceSummary.scala.html
  app/views/includes/duplicateSubmissionWarning.scala.html
  app/views/incomes/duplicateSubmissionWarning.scala.html
  app/views/incomes/yourIncomeCalculation.scala.html
  conf/messages
  conf/messages.cy
  conf/tai.routes
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
  test/views/html/IncomeSourceSummaryViewSpec.scala
  test/views/html/incomes/DuplicateSubmissionWarningSpec.scala
  test/views/html/incomes/yourIncomeCalculationSpec.scala
Labels: Team 8

#575 ST-467-2: Update cancel link content
  conf/messages
  conf/messages.cy
Labels: Team 8
