Repository hmrc/tai-frontend, pull requests merged in 2019-02, with the labels that each got.

#418 ST-523: Distinguish between verify and GG users for auth
  app/controllers/UnauthorisedController.scala
  app/controllers/auth/AuthAction.scala
  conf/tai.routes
  test/controllers/UnauthorisedControllerSpec.scala
  test/controllers/auth/AuthActionSpec.scala
Labels: Team 8

#421 ST-503: Updated content for potential underpayment page
  app/controllers/PotentialUnderpaymentController.scala
  app/uk/gov/hmrc/tai/util/Referral.scala
  app/uk/gov/hmrc/tai/viewModels/PotentialUnderpaymentViewModel.scala
  app/views/potentialUnderpayment.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/PotentialUnderpaymentControllerSpec.scala
  test/uk/gov/hmrc/tai/util/ReferralSpec.scala
  test/uk/gov/hmrc/tai/viewModels/PotentialUnderpaymentViewModelSpec.scala
  test/views/html/potentialUnderpaymentViewSpec.scala
Labels: Team 8

#425 ST-487b: Updated Welsh translation for radio button
  conf/messages.cy
Labels: Team 8

#434 ST-503-welsh: updated welsh translation for underpayment-estimate page
  conf/messages.cy
Labels: Team 8

#435 ST-503-welsh: changed type of apostrophe used in welsh to fix failing…
  conf/messages.cy
Labels: Team 8

#437 Dep-Upgrade: Updated library dependencies to latest version
  app/uk/gov/hmrc/tai/config/wiring.scala
  app/uk/gov/hmrc/tai/connectors/AuthClientAuthConnector.scala
  project/FrontendBuild.scala
  project/plugins.sbt
Labels: Team 8

#441 ST-430: fixed confirmIncomeIrregularHours to make NewAmountKey optional
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
Labels: Team 8

#436 ST-516: New content for IYA CY plus one
  app/views/potentialUnderpayment.scala.html
  conf/messages
  conf/messages.cy
  test/views/html/potentialUnderpaymentViewSpec.scala
Labels: Pending QA, Team 8

#446 dep-upgrade: Updated library dependencies to latest version
  project/FrontendBuild.scala
  project/plugins.sbt
Labels: Team 8

#449 Ddcnls 5481
  app/assets/js/urbanner.js
  app/assets/sass/tai11022019.scss
  app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
  app/views/main.scala.html
  conf/application.conf
  conf/messages
  conf/messages.cy
  test/mocks/MockTemplateRenderer.scala
  test/views/html/WhatDoYouWantToDoTileViewSpec.scala
Labels: Passed Review :+1:

#458 St 524
  app/assets/sass/tai11022019.scss
  app/controllers/IncomeController.scala
  app/controllers/IncomeSourceSummaryController.scala
  app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala
  app/uk/gov/hmrc/tai/service/TrackingService.scala
  app/uk/gov/hmrc/tai/service/journeyCompletion/JourneyCompletionService.scala
  app/uk/gov/hmrc/tai/util/constants/JourneyCacheConstants.scala
  app/uk/gov/hmrc/tai/viewModels/IncomeSourceSummaryViewModel.scala
  app/views/IncomeSourceSummary.scala.html
  conf/messages
  conf/messages.cy
  test/controllers/IncomeControllerSpec.scala
  test/controllers/IncomeSourceSummaryControllerSpec.scala
  test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
  test/uk/gov/hmrc/tai/service/journeyCompletion/EstimatedPayJourneyCompletionServiceSpec.scala
  test/uk/gov/hmrc/tai/viewModels/IncomeSourceSummaryViewModelSpec.scala
  test/views/html/IncomeSourceSummaryViewSpec.scala
Labels: Team 8

#457 success-banner-fix: Styling fix for responsivenes of the success bann…
  app/assets/sass/tai26022019.scss
  app/views/main.scala.html
Labels: Team 8
