Repository hmrc/tai-frontend, pull requests merged in 2019-05, with the labels that each got.

#550 ST-620: Accessibility improvements tax code change comparison page
  app/views/taxCodeChange/formattedTaxCodeForComparison.scala.html
  app/views/taxCodeChange/taxCodeComparison.scala.html
  conf/messages
  conf/messages.cy
  test/uk/gov/hmrc/tai/util/yourTaxFreeAmount/IabdTaxCodeChangeReasonsSpec.scala
  test/views/html/taxCodeChange/TaxCodeComparisonViewSpec.scala
Labels: PO/BA review pending, Pending QA, Team 8

#573 St 591
  app/views/taxCodeChange/yourTaxFreeAmount.scala.html
  conf/messages
  conf/messages.cy
  test/views/html/taxCodeChange/YourTaxFreeAmountViewSpec.scala
Labels: Team 8

#570 DDCNOS-5081: Change deep linked controllers to make API calls sequentially
  app/controllers/EstimatedIncomeTaxController.scala
  app/controllers/IncomeSourceSummaryController.scala
  app/controllers/TaxFreeAmountController.scala
Labels: Do not merge :stop_sign:

#590 DepUpgrade: Upgraded hmrctest to 3.8.0 as this was missed previously
  project/FrontendBuild.scala
Labels: Team 8
